spring.application.name=Expense-Tracker
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/expenseTrackerDB
spring.datasource.username=postgres
spring.datasource.password=root
server.port=8080
